### here is the playground for ranking the rowers. 
For now we will just rank people based on their heights. This way we will generate a naive ranking solution for Matcher()
Weights will be checked after that ranking, so that pairs (2:3; 4:5, etc.) have the right weight distribution

In [99]:
%pylab inline
import pandas as pd
import numpy as np
from collections import defaultdict

Populating the interactive namespace from numpy and matplotlib

In [134]:
dtypes = {'cox': bool,'name': str, 'height [cm]': np.float, 'weight [kg]': np.float, 'notes': str}
prefs = pd.read_csv('prefs.csv', sep=';', index_col=False, dtype=dtypes)

In [135]:
# accomodate to elina's preference of sitting in front, by manually setting her height to height = height + 7
prefs.loc[prefs['name'] == 'Elina', 'height [cm]'] = 172.0

In [136]:
prefs

,cox,name,height [cm],weight [kg],notes
0,True,Tiia,166.0,55.0,"rower/white oar, can cox 1/4"
1,False,Alison,164.0,64.1,Rower
2,False,Bulat,174.0,79.0,NaN
3,True,Arvydas,181.0,77.0,"Cox, white"
4,True,Julia,175.0,70.0,I usually do worse in the last two rows becaus...
5,False,Lauri,170.0,65.1,NaN
6,False,Tatiana,169.0,55.5,rower or white oar if needed
7,False,Ulrika,169.1,64.5,Rower or white if needed
8,True,Karen,173.5,67.5,"Rower 1st/2nd row, white oar (if needed), also..."
9,False,Hans,179.0,73.0,NaN
10,False,Jaana,167.0,62.0,want to change sides in every swich
11,False,Joseph,170.1,65.0,NaN
12,False,Elli,163.0,60.0,NaN
13,False,Elina,172.0,55.1,Rower in the front part of the boat
14,False,Kul,157.0,64.0,NaN

In [137]:
# create a dict object, where name: {weight, height, cox}
d = dict()
for i in range(len(prefs)):
    d[prefs.iloc[i,:]['name']] = {'height': prefs.iloc[i,:]['height [cm]'], 'weight': prefs.iloc[i,:]['weight [kg]'], 'cox': prefs.iloc[i,:]['cox']}

In [242]:
# prep for rankign 
heights = dict()
coxes = dict()
for k,v in d.items():
    heights[k]= v['height']
for k,v in d.items():
    coxes[k]= v['cox']
    
# ranking by height https://stackoverflow.com/questions/30282600/python-ranking-dictionary-return-rank

heights_rank = {key: rank for rank, key in enumerate(sorted(heights, key=heights.get, reverse=True), 1)}
for k, v in heights_rank.items():
    d[k]['rank_height'] = v  # do not modify in-place

In [243]:
dd = d.copy()

In [244]:
rng = np.random.RandomState(1234) # for reproducibility

for k, v in dd.items():
    out = list()
    if v['rank_height'] == 1: # for highest rank it is just range(1,15)
        rest = list(range(v['rank_height'],len(dd)))
        out = out + rest
    elif v['rank_height'] == len(dd): # for lowest rank it is arange(15,1,-1)
        rest = list(arange(v['rank_height'], 0,-1))
        out = out + rest
    elif v['rank_height'] < len(dd): # check that it is less than 15, then start building rest by +/- 1
        rest = [v['rank_height'],v['rank_height']+1,v['rank_height']-1]
        if v['rank_height']+1 < len(dd):
            rest = rest + [v['rank_height']+2,v['rank_height']-2]
        out = rest + list(rng.permutation(list(set(set(np.arange(1,15,1))).difference(rest))))  # here we get elements from range(1,15) that are not in rest, and then we shuffle them. list(set(set)) is needed because set returns ordered ??? values
    v['rank_height_full'] = out

#    dd[k]['rank_height_full'] = v['rank_height']

In [246]:
dd

{'Tiia': {'height': 166.0,
  'weight': 55.0,
  'cox': True,
  'rank_height': 12,
  'rank_height_full': [12, 13, 11, 14, 10, 9, 3, 2, 1, 8, 5, 6, 7, 4]},
 'Alison': {'height': 164.0,
  'weight': 64.1,
  'cox': False,
  'rank_height': 13,
  'rank_height_full': [13, 14, 12, 15, 11, 9, 6, 7, 1, 5, 4, 3, 10, 8, 2]},
 'Bulat': {'height': 174.0,
  'weight': 79.0,
  'cox': False,
  'rank_height': 4,
  'rank_height_full': [4, 5, 3, 6, 2, 9, 12, 8, 7, 13, 11, 10, 1, 14]},
 'Arvydas': {'height': 181.0,
  'weight': 77.0,
  'cox': True,
  'rank_height': 1,
  'rank_height_full': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]},
 'Julia': {'height': 175.0,
  'weight': 70.0,
  'cox': True,
  'rank_height': 3,
  'rank_height_full': [3, 4, 2, 5, 1, 13, 7, 12, 11, 14, 10, 9, 6, 8]},
 'Lauri': {'height': 170.0,
  'weight': 65.1,
  'cox': False,
  'rank_height': 8,
  'rank_height_full': [8, 9, 7, 10, 6, 5, 11, 3, 12, 14, 2, 1, 4, 13]},
 'Tatiana': {'height': 169.0,
  'weight': 55.5,
  'cox': False,
  'rank_height': 10,
  'rank_height_full': [10, 11, 9, 12, 8, 1, 6, 5, 14, 3, 7, 13, 4, 2]},
 'Ulrika': {'height': 169.1,
  'weight': 64.5,
  'cox': False,
  'rank_height': 9,
  'rank_height_full': [9, 10, 8, 11, 7, 12, 1, 6, 2, 14, 4, 3, 5, 13]},
 'Karen': {'height': 173.5,
  'weight': 67.5,
  'cox': True,
  'rank_height': 5,
  'rank_height_full': [5, 6, 4, 7, 3, 14, 8, 13, 9, 2, 12, 11, 10, 1]},
 'Hans': {'height': 179.0,
  'weight': 73.0,
  'cox': False,
  'rank_height': 2,
  'rank_height_full': [2, 3, 1, 4, 0, 12, 7, 8, 13, 11, 6, 5, 10, 9, 14]},
 'Jaana': {'height': 167.0,
  'weight': 62.0,
  'cox': False,
  'rank_height': 11,
  'rank_height_full': [11, 12, 10, 13, 9, 6, 1, 2, 8, 4, 3, 5, 7, 14]},
 'Joseph': {'height': 170.1,
  'weight': 65.0,
  'cox': False,
  'rank_height': 7,
  'rank_height_full': [7, 8, 6, 9, 5, 13, 1, 2, 4, 10, 14, 3, 12, 11]},
 'Elli': {'height': 163.0,
  'weight': 60.0,
  'cox': False,
  'rank_height': 14,
  'rank_height_full': [14, 15, 13, 1, 6, 2, 4, 8, 10, 11, 9, 3, 12, 5, 7]},
 'Elina': {'height': 172.0,
  'weight': 55.1,
  'cox': False,
  'rank_height': 6,
  'rank_height_full': [6, 7, 5, 8, 4, 14, 9, 11, 1, 12, 10, 2, 3, 13]},
 'Kul': {'height': 157.0,
  'weight': 64.0,
  'cox': False,
  'rank_height': 15,
  'rank_height_full': [15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]}}